name: CI Workflow with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-push-to-registry:

    runs-on: ubuntu-latest

    steps:
      - name: Check out codebase
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build jar with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ikaravai/ci-cd-test
          tags: v2.0.$GITHUB_RUN_NUMBER
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
